name: go_getter
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - jpeg=9e=h0b41bf4_3
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_4
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.9.0=20_linux64_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.2.0=hf544144_3
  - libuuid=2.41.2=h5347b49_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - matplotlib=3.3.0=1
  - matplotlib-base=3.3.0=py38h91b0d89_1
  - ncurses=6.5=h2d0b736_3
  - numpy=1.20.2=py38h9894fe3_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.4.4=py38h47df419_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pillow=8.2.0=py38ha0e1e83_1
  - pip=24.3.1=pyh8b19718_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - python=3.8.19=hd12c33a_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - readline=8.3=h853b02a_0
  - scipy=1.9.1=py38hea3f02b_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=59.8.0=py38h578d9bd_1
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.13.2=py38h71d37f0_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py38hfb59056_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/ely67071/.conda/envs/go_getter
